---
title: "Methods for variance esitmation of high dimensional data"
author: "Xuelong Wang"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true
    keep_tex: FALSE
bibliography: bibliography.bib
header-includes:
    - \usepackage{float,amsmath, bbm, amssymb, siunitx, bm}
    - \usepackage{pdfpages}
    - \floatplacement{figure}{H}
    - \newcommand{\indep}{\rotatebox[origin=c]{90}{$\models$}}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      comment = "", 
                      message = FALSE, 
                      warning = FALSE, 
                      echo = FALSE, 
                      fig.height = 5,
                      fig.width = 8,
                      root.dir = "~/dev/projects/Chen_environmental_study/")
options(scipen=1, digits=2)

# load library
library(MASS)
library(tidyverse)
library(data.table)
library(ggforce)
library(ggpubr)
library(gridExtra)
library(kableExtra)
library(knitr)
```

# Motivation

# Linear regression

```{r, child='GCTA.Rmd', cache=TRUE}
```

```{r, child="EigenPrism.Rmd", cache=FALSE}
```

```{r, child='Dicker_2013.Rmd', cache=FALSE}
```

# References

