---
title: "data_tran_hist
author: "Xuelong Wang"
date: "`r Sys.Date()`"
output: 
  html_document: 
    fig_caption: yes
    fig_width: 18
    theme: united
    toc: true
    number_sections: true
---

```{r, include=FALSE}
knitr::opts_knit$set(root.dir = "~/dev/projects/Chen_environmental_study/")
source("./R_code/Yang_REML.R")
options(width = 100)
library(ggplot2)
library(tidyverse)
library(sas7bdat)
library(printr)

load("./result/simulation_result_reproduce_with_rep_beta")

#####################################################################################
## figures number function
#####################################################################################
# A function for captioning and referencing images
fig <- local({
    i <- 0
    ref <- list()
    list(
        cap=function(refName, text) {
            i <<- i + 1
            ref[[refName]] <<- i
            paste("Figure ", i, ": ", text, sep="")
        },
        ref=function(refName) {
            ref[[refName]]
        })
})

#####################################################################################
## figures number function
#####################################################################################
# A function for captioning and referencing tables

tab <- local({
    i <- 0
    ref <- list()
    list(
        cap=function(refName, text) {
            i <<- i + 1
            ref[[refName]] <<- i
            paste("Table ", i, ": ", text, sep="")
        },
        ref=function(refName) {
            ref[[refName]]
        })
})
```

```{r, echo = FALSE}


```

