---
title: "Categorize_simulation"
author: "Xuelong Wang"
date: "`r Sys.Date()`"
output: 
  html_document: 
    fig_caption: yes
    fig_width: 20
    theme: united
    toc: true
    number_sections: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/dev/projects/Chen_environmental_study/")
options(width = 100)
library(ggplot2)
library(tidyverse)
library(sas7bdat)
library(printr)

#####################################################################################
## figures number function
#####################################################################################
# A function for captioning and referencing images
fig <- local({
    i <- 0
    ref <- list()
    list(
        cap=function(refName, text) {
            i <<- i + 1
            ref[[refName]] <<- i
            paste("Figure ", i, ": ", text, sep="")
        },
        ref=function(refName) {
            ref[[refName]]
        })
})

#####################################################################################
## figures number function
#####################################################################################
# A function for captioning and referencing tables

tab <- local({
    i <- 0
    ref <- list()
    list(
        cap=function(refName, text) {
            i <<- i + 1
            ref[[refName]] <<- i
            paste("Table ", i, ": ", text, sep="")
        },
        ref=function(refName) {
            ref[[refName]]
        })
})

#####################################################################################
## calculate MSE for the result 
#####################################################################################
sum_fn <- function(x) {
  x <- x[x[,1]!=0,]
  c(colMeans((x[,c(3,4)] -x[,c(1,2)])^2), colMeans((x[,c(5,6)] -x[,c(1,2)])^2))}

#####################################################################################
## plot function
#####################################################################################
plot_fn <- function(x, names) {
    x <- x[x[,1]!=0,]
    g1<- ggplot(tidyr::gather(data.frame(x[,c(1,3,5)])), aes(value, fill = key, y = ..density..)) +
    geom_histogram(alpha = 0.2, position = "identity", binwidth =  0.5) +
    geom_density(alpha = 0.2) +
    xlim(-20,20)+
    scale_fill_discrete(name="Methods",
                        labels=c("Original GCTA", "Proposed Method", "True value"))+
    theme(legend.title = element_text(size=25), plot.title = element_text(size = 30, face = "bold"))+
    ggtitle(paste0("main_total_effect_",names))
  
  
    g2 <- ggplot(tidyr::gather(data.frame(x[,c(2,4,6)])), aes(value, fill = key, y = ..density..)) +
    geom_histogram(alpha = 0.2, position = "identity", binwidth =  0.5) +
    geom_density(alpha = 0.2) +
    xlim(0,20)+
    scale_fill_discrete(name="Methods",
                        labels=c("Original GCTA", "Proposed Method", "True value"))+
    theme(legend.title = element_text(size=25), plot.title = element_text(size = 30, face = "bold"))+
    ggtitle(paste0("interaction_total_effect_",names))
    
    gridExtra::grid.arrange(g1, g2, ncol=2)
}

box_plot_fn <- function(x, names){
  x <- x[x[,1]!=0,]
  g1 <- ggplot(tidyr::gather(data.frame(x[,c(1,3,5)])), aes(x = key, y = value, color = key)) + 
    geom_boxplot() +
    ylim(-20,20)+
    labs(x = "method", y = "Variance")+
    scale_color_discrete(name="Methods",
                        labels=c("Original GCTA", "Proposed Method", "True value"))+
    theme(legend.title = element_text(size=25), plot.title = element_text(size = 30, face = "bold"))+
    ggtitle(paste0("main_total_effect_",names))
  
  g2 <- ggplot(tidyr::gather(data.frame(x[,c(2,4,6)])), aes(x = key, y = value, color = key)) + 
    geom_boxplot() +
    ylim(0, 20)+
    labs(x = "method", y = "Variance")+
    scale_color_discrete(name="Methods",
                        labels=c("Original GCTA", "Proposed Method", "True value"))+
    theme(legend.title = element_text(size=25), plot.title = element_text(size = 30, face = "bold"))+
    ggtitle(paste0("interaction_total_effect_",names))
    
  gridExtra::grid.arrange(g1, g2, ncol=2)
}
```

```{r loading result, include=FALSE}
source("./R_code/Yang_REML.R")

```

# Tranformation results 


# Simulation result on the subset of PCB data

## rank tranformation

```{r, echo=FALSE}
load("./result/simulation_quantile_2_5")
out_table <- t(sum_fn(result_list$b_quantile_2))
rownames(out_table) <- "MSE"

knitr::kable(x = out_table, 
             row.names = TRUE,
             format = "html",
             caption = tab$cap("rank","MSE of estimated variance with 2 categories for each covariate"))  %>% 
  kableExtra::kable_styling(full_width = FALSE)
```


```{r , echo = FALSE, warning=FALSE, fig.cap=fig$cap("b_quantile_2_box", "Box-plot of Main and Interaction variance with 2 categories for each covariate")}
  box_plot_fn(result_list$b_quantile_2,"b_quantile_2")
```

```{r , echo = FALSE, warning=FALSE, fig.cap=fig$cap("b_quantile_2_hist", "Histogram of Main and Interaction variance with 2 categories for each covariate")}
  plot_fn(result_list$b_quantile_2,"b_quantile_2")
```

## Categorize into 5 levels

```{r, echo=FALSE}
load("./result/simulation_quantile_2_5")
out_table <- t(sum_fn(result_list$b_quantile_5))
rownames(out_table) <- "MSE"

knitr::kable(x = out_table, 
             row.names = TRUE,
             format = "html",
             caption = tab$cap("rank","MSE of estimated variance with 5 categories for each covariate"))  %>% 
  kableExtra::kable_styling(full_width = FALSE)
```


```{r , echo = FALSE, warning=FALSE, fig.cap=fig$cap("b_quantile_5_box", "Box-plot of Main and Interaction variance with 5 categories for each covariate")}
  box_plot_fn(result_list$b_quantile_5,"b_quantile_5")
```

```{r , echo = FALSE, warning=FALSE, fig.cap=fig$cap("b_quantile_5_hist", "Histogram of Main and Interaction variance with 5 categories for each covariate")}
  plot_fn(result_list$b_quantile_5,"b_quantile_5")
```