---
title: "Correlation_simuation"
author: "Xuelong Wang"
date: "`r Sys.Date()`"
output: 
  html_document: 
    fig_caption: yes
    fig_width: 18
    theme: united
    toc: true
    number_sections: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/dev/projects/Chen_environmental_study/")
options(width = 100)
library(ggplot2)
library(tidyverse)
library(sas7bdat)
library(printr)

#####################################################################################
## figures number function
#####################################################################################
# A function for captioning and referencing images
fig <- local({
    i <- 0
    ref <- list()
    list(
        cap=function(refName, text) {
            i <<- i + 1
            ref[[refName]] <<- i
            paste("Figure ", i, ": ", text, sep="")
        },
        ref=function(refName) {
            ref[[refName]]
        })
})

#####################################################################################
## figures number function
#####################################################################################
# A function for captioning and referencing tables

tab <- local({
    i <- 0
    ref <- list()
    list(
        cap=function(refName, text) {
            i <<- i + 1
            ref[[refName]] <<- i
            paste("Table ", i, ": ", text, sep="")
        },
        ref=function(refName) {
            ref[[refName]]
        })
})

#####################################################################################
## calculate MSE for the result 
#####################################################################################
sum_fn <- function(x) {
  x <- x[x[,1]!=0,]
  c(colMeans((x[,c(3,4)] -x[,c(1,2)])^2), colMeans((x[,c(5,6)] -x[,c(1,2)])^2))}

#####################################################################################
## plot function
#####################################################################################
plot_fn <- function(x, names) {
    x <- x[x[,1]!=0,]
    g1<- ggplot(tidyr::gather(data.frame(x[,c(1,3,5)])), aes(value, fill = key, y = ..density..)) +
    geom_histogram(alpha = 0.2, position = "identity", binwidth =  0.5) +
    geom_density(alpha = 0.2) +
    xlim(-20,20)+
    labs(fill="Methods")+
    ggtitle(paste0("main_total_effect_",names))
  
    g2 <- ggplot(tidyr::gather(data.frame(x[,c(2,4,6)])), aes(value, fill = key, y = ..density..)) +
    geom_histogram(alpha = 0.2, position = "identity", binwidth =  0.5) +
    geom_density(alpha = 0.2) +
    xlim(0,20)+
    labs(fill="Methods")+
    ggtitle(paste0("interaction_total_effect_",names))
    
    gridExtra::grid.arrange(g1, g2, ncol=2)
}

box_plot_fn <- function(x, names){
  x <- x[x[,1]!=0,]
  g1 <- ggplot(tidyr::gather(data.frame(x[,c(1,3,5)])), aes(x = key, y = value, color = key)) + 
    geom_boxplot() +
    ylim(-20,20)+
    labs(color ="Methods")+
    labs(x = "method", y = "Variance")+
    ggtitle(paste0("main_total_effect_",names))
  
  g2 <- ggplot(tidyr::gather(data.frame(x[,c(2,4,6)])), aes(x = key, y = value, color = key)) + 
    geom_boxplot() +
    ylim(0, 20)+
    labs(color ="Methods")+
    labs(x = "method", y = "Variance")+
    ggtitle(paste0("interaction_total_effect_",names))
    
  gridExtra::grid.arrange(g1, g2, ncol=2)
}
```

```{r loading result, include=FALSE}
source("./R_code/Yang_REML.R")
```

# Uncorrelation method 
```{r calcuate cov, echo=FALSE}
a=read.sas7bdat("~/dev/projects/Chen_environmental_study/R_code/pcbs1000nomiss.sas7bdat")
a=data.matrix(a[,2:35], rownames.force = NA)
b <- a
b_null <- std_fn(b, ncol(b), tran_FUN = null_tran) 
b_rank <- std_fn(b, ncol(b), tran_FUN = rank_tran) 
b_quantile <- std_fn(b, ncol(b), tran_FUN = norm_quantile_tran) 

cov_null <- uncorr_fn(b_null) %>% cov
cov_rank <- uncorr_fn(b_rank) %>% cov
cov_quantile <- uncorr_fn(b_quantile) %>% cov
```

```{r print result, tidy=TRUE}
cov_null[1:10,1:10]
cov_rank[1:10,1:10]
cov_quantile[1:10,1:10]
```

```{r intercation}
cov_null_interaction <- 
```
