---
title: "Normal_cor_simulation"
author: "Xuelong Wang"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true
    keep_tex: true
    fig_width: 12
    fig_height: 10
header-includes:
    - \usepackage{float,amsmath, bbm, siunitx, bm}
    - \floatplacement{figure}{H}
    - \newcommand{\indep}{\rotatebox[origin=c]{90}{$\models$}}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
library(ggplot2)
knitr::opts_chunk$set(echo = FALSE)

# change to the long talble formate so that it can work with ggplot)(fill and gird)
data_clean_fn <- function(x) {
  y = fread(x); 
  y <- y[,-1]; 
  names(y)[1:6] <- c("true_main", "true_interaction", "GCTA_main", "GCTA_interaction", "prop_main", "prop_interaction")
  y_tmp <- tidyr::gather(data.frame(y[,1:6]));
  y_final <- cbind(y_tmp, y[,7:ncol(y)])
  }
```

# Motivation



# Simulation result 

## Setup



### Averaged estimation

```{r full data, results='asis'}
load("~/dev/projects/Chen_environmental_study/result/simulation_norm_core_rank")
for(i in 1:length(result_list)){
  
out_table <- result_list[[i]]

out_table <- out_table[,c(1,3,5,2,4,6)]

knitr::kable(x = out_table,
             format = "latex",
             caption = gsub("_", "-", names(result_list)[i]))  %>% # replace _ by - b/c latex 
  kableExtra::add_header_above(., c("Main" = 3, "Interaction" = 3)) %>% 
  kableExtra::kable_styling(., full_width = FALSE,
                            latex_options = c("striped", "hold_position"),
                            stripe_color = "gray!80")  %>%
  print(.)
}
```

\clearpage

### Histgram of 100 iterations

```{r Histgram full data}

input_file <- list.files("~/dev/projects/Chen_environmental_study/result/inter_result/norm_cor/")  %>% paste0("~/dev/projects/Chen_environmental_study/result/inter_result/norm_cor/",.)

file_path <- input_file[grepl(c("rank_1"),input_file, perl=TRUE)]
input_table <- lapply(file_path, FUN = data_clean_fn ) %>% rbindlist(., fill = TRUE)
input_table[,("cor") := as.character(input_table[["cor"]])] # chage the formate into character so that it can print out correctly
```

```{r normal_main}
ggplot(data = input_table[grepl("main",key, perl=TRUE)], aes(x = key, y = value, fill = key)) +
  geom_violin(alpha = 0.2) +
  geom_boxplot(alpha = 0.7) +
  facet_wrap(facets = vars(cor, tran), ncol = 3, scales = "free") +
  ggtitle(paste0("Main_effect_Normal_cor")) 
  
```

```{r normal_inter}
ggplot(data = input_table[grepl("interaction",key, perl=TRUE)], aes(x = key, y = value, fill = key)) +
  geom_violin(alpha = 0.2) +
  geom_boxplot(alpha = 0.7) +
  facet_wrap(facets = vars(cor, tran), ncol = 3, scales = "free") +
  ggtitle(paste0("Interactive_effect_Normal_cor")) 
```




# Conclusion

# Further work
