---
title: "Inference methods of high dimensional variance estimator report"
author: "Xuelong Wang"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true
    keep_tex: FALSE
header-includes:
    - \usepackage{float,amsmath, bbm, amssymb, siunitx, bm}
    - \usepackage{pdfpages}
    - \floatplacement{figure}{H}
    - \newcommand{\indep}{\rotatebox[origin=c]{90}{$\models$}}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      comment = "", 
                      message = FALSE, 
                      warning = FALSE, 
                      echo = FALSE, 
                      fig.height = 5,
                      fig.width = 8,
                      root.dir = "~/dev/projects/Chen_environmental_study/reports/proposed_GCTA_paper/est_var_analysis/est_combined_data/jackknife/jackknife_report/")
options(scipen=1, digits=2)

# load library
library(MASS)
library(tidyverse)
library(data.table)
library(ggforce)
library(ggpubr)
library(gridExtra)
library(kableExtra)
library(knitr)
```

# Motivation

# Subsampling method: Jackknife

```{r child = "Jackknife_variance.Rmd"}
```

## functional of distribution functions 

## variance estimation for high dimensional data 

## Jackknife variance estimation on high dimension signal estimation

```{r child = "variance_inflation_n_p.Rmd"}
```

### After bias correction

# Subsampling method: bootstrap 

## non-parameteric bootstrap 

## parametric bootstrap


